server:
  port: 10010
spring:
  application:
    name: hxq-zuul
zuul:
  routes:
    service-provider: /user/** #这里的service-provider是服务名
    service-consumer: /consumer/**
  prefix: /api # 路由前缀

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
