server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.31.14
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4GGkpf5aY2sYhXJ1T7T2 # 你自己的accessKeyId
    accessKeySecret: dp5Bz3Gzw5tG6c0un2VxoUFmVBVLTZ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_200713858 # 模板名称